### ISSUE TITLE
OVH Telecom scan: json: cannot unmarshal object into Go value of type []suppliers.OVHAPIResponseNumber

### ISSUE THREAD

**Issue by Andrejki** [sundowndev/phoneinfoga#1106]
**Describe the bug**
This is the output on the web interface.

I used this command:
The number on the web local interface in the format "+12413251251"
The format is good. 

**Expected behavior**
No errors? And all the info about where is phone number registered e.g?

**`OVH Telecom scan: json: cannot unmarshal object into Go value of type []suppliers.OVHAPIResponseNumber`** **ERROR**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 
 - PhoneInfoga exact version - the command doesn t wont to run. 
 It is the latest, I ve tried it this day.

**Additional context**
BTW, I find this not to be useful like popular it is. All that I do get are google dorks that are even without any results in 98% of the cases. I really don t see why is this tool popular? I had much better results with Holehe or any other. 
Maybe I am missing something, thank you for creating it, though.
Best regards.

**Comment by sauhardo2020** [comment]
hey Andrjki i am having the same problem can you tell me the name of some other tools like phoneinfoga that i can use

**Comment by Andrejki** [comment]
> hey Andrjki i am having the same problem can you tell me the name of some other tools like phoneinfoga that i can use

Snoop Project. Explore Maigret bot on Telegram. And many other bots that I can t recall now.

**Comment by sundowndev** [comment]
> OVH Telecom scan: json: cannot unmarshal object into Go value of type []suppliers.OVHAPIResponseNumber ERROR

This is due to US-based numbers not being supported by this API. This will be fixed soon by #1108.

>  BTW, I find this not to be useful like popular it is. All that I do get are google dorks that are even without any results in 98% of the cases. I really don t see why is this tool popular? I had much better results with Holehe or any other.
Maybe I am missing something, thank you for creating it, though.

Results you get from this tool depends on several factors:
- The given phone number is valid and has actual footprints on the web
- You took time to configure all scanners properly

Still, I agree that the output of the tool is limited at this time. This will change with the introduction of several new scanners in the future. I'm doing a rework of the scanner API and the UI. That rework is covered in https://github.com/sundowndev/phoneinfoga/issues/967.
