### ISSUE TITLE
Nothing Working

### ISSUE THREAD

**Issue by M3Ga98** [sundowndev/PhoneInfoga#527]
I got the latest version of phoneinfoga (v2.3.3) but nothing is working, it just keeps getting me useless links. I tried with so many numbers from many different countries. I even tried with numbers that I got from a manual google search, and still, phoneinfoga can't get a thing.

I run ./phoneinfoa scan -n "THE NUMBER WRITTEN CORRECTLY"

I expected to get any result from any search of any number, but what can I say ....

I'm using Kali Linux 2020.2

**Comment by AlanShiah** [comment]
I'm pretty sure thats not how you run the command. Change directories to the phoneinfoga directory. (Do it twice if there are two of them inside each other) and then run the command python3 phoneinfoga.py -n (phone number) (options). I also use kali 2020.2

**Comment by M3Ga98** [comment]
![Screenshot from 2020-10-23 21-12-36](https://user-images.githubusercontent.com/28842134/97044690-bd39bf00-1574-11eb-965f-2763925c11a5.png)

**Comment by M3Ga98** [comment]
it's an executable not a python file

**Comment by sundowndev** [comment]
@M3Ga98 Please provide the output of the scan, optionally with sensitive information hidden. Remember this is just a tool that uses external services along with basic local data.

About Google links: https://github.com/sundowndev/PhoneInfoga/issues/502#issuecomment-707062581

**Comment by Kevinscki** [comment]
Are the two tools similar **(phoneinphoga.py & phoneinfoga)** because I remember using phoneinfoga.py and gave slightly more reliable data than phoneinfoga itself (yes the gui is there, but where is the real content)
my guess is that maybe you require a lot off API dependencies for the phoneinfoga to work, however now phoneinfoga.py raises errors, and not sure how to solve them, I tested on UNIX and Windows platform still get errors with phoneinfoga.py
