### ISSUE TITLE
Use DuckDuckGo instead of Google for dorking

### ISSUE THREAD

**Issue by PaS3** [sundowndev/phoneinfoga#750]
If you use Duckduckgo.com does the google dorks work?

`https://duckduckgo.com/?t=ffnt&q=site:facebook OR "you"`

I am sick of the recaptcha  on google.

Never seen a recap on the Duck, and tempted by their donation links.

**Comment by PaS3** [comment]
If Duck is good, could you include next release on docker image web interface.

**Comment by sundowndev** [comment]
Hi, yes it's possible but since DDG has not the same dork interface than Google, a new scanner must added to achieve that. I don't have much time to work on this at the moment so feel free to contribute by submitting a PR! [Dorkgen](https://github.com/sundowndev/dorkgen) is already compatible with DDG.

**Comment by PaS3** [comment]
Thanks, will do a PR when I find some time.

**Comment by sundowndev** [comment]
Supporting Duckduckgo has been abandoned in favor of the new googlecse scanner. Feel free to create a plugin to support it.
