### ISSUE TITLE
Error selenium

### ISSUE THREAD

**Issue by thesuhu** [sundowndev/PhoneInfoga#83]
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

How do I fix this? Thanks

**Comment by thesuhu** [comment]
When I reinstall step by step in documentation, I got error this

File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 1520, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'geckodriver'
$

**Comment by sundowndev** [comment]
It seems you didn't installed geckodriver properly. See [this comment on stackoverflow](https://stackoverflow.com/a/40437690).

1. Are you using Docker ?
2. What command did you run ?
3. What is your OS ?
4. Do you have the latest version of Firefox installed ?
5. What is the output of `geckodriver --version` ?

**Comment by thesuhu** [comment]
1. I am using termux
2. python3 phoneinfoga.py -n +62xxxxxxxxxx
3. I am using android 
4. Should I install Firefox on termux?
5. geckodriver --version                                bash: /data/data/com.termux/files/usr/bin/geckodriver: cannot execute binary file: Exec format error

I am using this geckodriver geckodriver-v0.24.0-linux64.tar.gz
 
Thanks

**Comment by sundowndev** [comment]
I'm sorry but the tool wasn't designed to be used on Android, and I don't want to explicitly support it. I don't even know if you can use the Selenium package on it.

Two options :
- Investigate on this issue about Geckodriver/Selenium usage on Android
- Don't use the latest version of the tool but the old version that uses request library instead of geckodriver (might be buggy)

If you want to hack the tool to be usable on Android too, feel free to fork it and make a pull request to add the support!

Here's the last commit where the tool was using request library : https://github.com/sundowndev/PhoneInfoga/tree/acb8519fe861756411c9ef130638509522db04e1

You switch on it by doing : 

```shell
git checkout acb8519fe861756411c9ef130638509522db04e1
```

**Comment by thesuhu** [comment]
Ok thank you
